import { eRouteURL, eNodeType, eNodeCategory, MenuNode } from "./common.model";

export const headerData = [
  {
    order: 1,
    type: eNodeType.ROUTE,
    iconClass: "volunteer_activism",
    name: "donate",
    url: eRouteURL.DONATE,  
    category: eNodeCategory.NAV,  
    visible: true,   
  },
  {
    order: 2,
    type: eNodeType.ROUTE,
    iconClass: "alarm",
    name: "prayers",
    url: eRouteURL.PRAYER,  
    category: eNodeCategory.NAV,    
    visible: true,   
  },
  {
    order: 3,
    type: eNodeType.ROUTE,
    iconClass: "perm_phone_msg",
    name: "contact",
    url: eRouteURL.CONTACT,  
    category: eNodeCategory.NAV,    
    visible: true,   
  },
  {
    order: 4,
    type: eNodeType.ROUTE,
    iconClass: "group",
    name: "admin",
    url: eRouteURL.ADMIN, 
    category: eNodeCategory.NAV,    
    visible: false,   
  },
  {
    order: 5,
    type: eNodeType.EVENT,
    iconClass: "menu",
    name: "menu",
    category: eNodeCategory.MENU,    
    visible: true,   
  },
  {
    order: 5,
    type: eNodeType.ROUTE,
    iconClass: "mosque",
    name: "F M C S",
    url: eRouteURL.HOME,
    category: eNodeCategory.BRAND,   
    visible: true,   
  },
] as Array<MenuNode>;

export const headerMobileData = [
  {
    order: 1,
    type: eNodeType.ROUTE,
    iconClass: "mosque",
    name: "home",
    url: eRouteURL.HOME,
    category: eNodeCategory.NAV,   
    visible: true,   
  },
  {
    order: 2,
    type: eNodeType.ROUTE,
    iconClass: "volunteer_activism",
    name: "donate",
    url: eRouteURL.DONATE,  
    category: eNodeCategory.NAV,  
    visible: true,   
  },
  {
    order: 3,
    type: eNodeType.ROUTE,
    iconClass: "alarm",
    name: "prayers",
    url: eRouteURL.PRAYER,  
    category: eNodeCategory.NAV,  
    visible: true,   
  },
  {
    order: 4,
    type: eNodeType.EVENT,
    iconClass: "menu",
    name: "menu",
    category: eNodeCategory.MENU,    
    visible: true,   
  },
] as Array<MenuNode>;
